name: "🐛 Bug Report"
description: "Found something wrong? Report a bug to help us improve."
title: "[BUG] - "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ![AWS Community Day Cebu Banner](https://your-image-host.com/banner-small.png)
        **Thank you for helping make our website better!**
        A detailed bug report helps our community fix issues faster. Please provide as much information as possible.

  - type: textarea
    id: description
    attributes:
      label: "🐞 The Bug"
      description: "A clear and concise description of what you found."
      placeholder: "When I click the 'Register' button on mobile, the page scrolls to the bottom instead of opening the registration link."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "🔁 Steps to Reproduce"
      description: "How can we make the bug happen? Please be specific."
      value: |
        1. Go to page '...'
        2. Using browser '...' on device '...'
        3. Click on button '....'
        4. See the unexpected behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen instead?"
      placeholder: "I expected a new tab to open with the event registration page."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: "🌐 Browser"
      description: "What browser were you using?"
      options:
        - "Google Chrome"
        - "Mozilla Firefox"
        - "Microsoft Edge"
        - "Safari"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "📸 Screenshots & Additional Context"
      description: "If applicable, add screenshots to help explain your problem. You can drag and drop images directly into this text area."

  - type: checkboxes
    id: final-checks
    attributes:
      label: "Final Checks"
      options:
        - label: "I have searched for existing issues and this is not a duplicate."
          required: true
        - label: "I agree to follow this project's Code of Conduct."
          required: true